<%- | 
  String[1] $cachesize,
| -%>
FROM varnish:6.2
ARG cachesize=<%= $cachesize %>

COPY default.vcl /etc/varnish/
RUN sed -i -r "s/malloc,256m/malloc,${cachesize}/g" /lib/systemd/system/varnish.service


